### PR TITLE
Do a `uname` version check before using `statx` on Android.

### LINKED ISSUE #311: `stat` crashes on Android
Syscalls `open2` and `statx` are not available on some Android devices and thus calling them causes seccomp to kill the process directly.

Here are the crash logs from two devices:

```
04-09 16:31:57.811 19810 19810 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-09 16:31:57.811 19810 19810 F DEBUG   : Build fingerprint: 'HUAWEI/HMA-AL00/HWHMA:10/HUAWEIHMA-AL00/10.1.0.163C00:user/release-keys'
04-09 16:31:57.812 19810 19810 F DEBUG   : Revision: '0'
04-09 16:31:57.812 19810 19810 F DEBUG   : ABI: 'arm64'
04-09 16:31:57.814 19810 19810 F DEBUG   : SYSVMTYPE: Maple
04-09 16:31:57.814 19810 19810 F DEBUG   : APPVMTYPE: Art
04-09 16:31:57.815 19810 19810 F DEBUG   : Timestamp: 2023-04-09 16:31:57+0800
04-09 16:31:57.815 19810 19810 F DEBUG   : pid: 19607, tid: 19649, name: Thread-3  >>> org.flos.phira <<<
04-09 16:31:57.815 19810 19810 F DEBUG   : uid: 10397
04-09 16:31:57.815 19810 19810 F DEBUG   : signal 31 (SIGSYS), code 1 (SYS_SECCOMP), fault addr --------
04-09 16:31:57.815 19810 19810 F DEBUG   : Cause: seccomp prevented call to disallowed arm64 system call 291
04-09 16:31:57.815 19810 19810 F DEBUG   :     x0  0000000000000066  x1  0000007487e2af40  x2  0000000000000100  x3  0000000000000fff
04-09 16:31:57.815 19810 19810 F DEBUG   :     x4  0000007487e2ac60  x5  0000000074617473  x6  0000000074617473  x7  0000000078746174
04-09 16:31:57.815 19810 19810 F DEBUG   :     x8  0000000000000123  x9  0000000000000001  x10 0000000000004001  x11 0000000000000000
04-09 16:31:57.815 19810 19810 F DEBUG   :     x12 0000007580e21223  x13 0000007580e23a00  x14 00000074881b45cc  x15 0000000000000003
04-09 16:31:57.815 19810 19810 F DEBUG   :     x16 0000007488d592e8  x17 000000757e42cba0  x18 0000007486fd2000  x19 0000007487e2ae38
04-09 16:31:57.815 19810 19810 F DEBUG   :     x20 0000007487e2af40  x21 0000000000000fff  x22 0000000000000100  x23 0000000000000066
04-09 16:31:57.815 19810 19810 F DEBUG   :     x24 00000074e8fed840  x25 0000007487e2af40  x26 0000000000000025  x27 0000007488d66000
04-09 16:31:57.815 19810 19810 F DEBUG   :     x28 00000074880ce58e  x29 0000000000000000
04-09 16:31:57.815 19810 19810 F DEBUG   :     sp  0000007487e2ab60  lr  00000074889908e8  pc  000000757e42cbc0
```

```
04-09 00:34:33.772  5968  5968 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-09 00:34:33.772  5968  5968 F DEBUG   : Build fingerprint: 'Redmi/rubens/rubens:13/TP1A.220624.014/V14.0.23.4.2.DEV:user/release-keys'
04-09 00:34:33.772  5968  5968 F DEBUG   : Revision: '0'
04-09 00:34:33.772  5968  5968 F DEBUG   : ABI: 'arm64'
04-09 00:34:33.772  5968  5968 F DEBUG   : Timestamp: 2023-04-09 00:34:32.513516823+0800
04-09 00:34:33.772  5968  5968 F DEBUG   : Process uptime: 6s
04-09 00:34:33.772  5968  5968 F DEBUG   : Cmdline: org.phira
04-09 00:34:33.772  5968  5968 F DEBUG   : pid: 5723, tid: 5755, name: Thread-4  >>> org.phira <<<
04-09 00:34:33.772  5968  5968 F DEBUG   : uid: 10195
04-09 00:34:33.772  5968  5968 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
04-09 00:34:33.772  5968  5968 F DEBUG   : signal 31 (SIGSYS), code 1 (SYS_SECCOMP), fault addr --------
04-09 00:34:33.772  5968  5968 F DEBUG   : Cause: seccomp prevented call to disallowed arm64 system call 437
04-09 00:34:33.772  5968  5968 F DEBUG   :     x0  0000000000000094  x1  00000078e7d29418  x2  00000078e7d293a0  x3  0000000000000018
04-09 00:34:33.772  5968  5968 F DEBUG   :     x4  000000000000000a  x5  00000000666e693a  x6  00000000666e693a  x7  000000006f666e69
04-09 00:34:33.772  5968  5968 F DEBUG   :     x8  00000000000001b5  x9  0000000000000000  x10 0000000a00000000  x11 000000000000000a
04-09 00:34:33.772  5968  5968 F DEBUG   :     x12 0000000000000000  x13 00000000ffffffbf  x14 00000078ea360b99  x15 0000000000000003
04-09 00:34:33.772  5968  5968 F DEBUG   :     x16 00000078eae163b8  x17 0000007a046a40c0  x18 00000078e78e8000  x19 00000078e7d29630
04-09 00:34:33.772  5968  5968 F DEBUG   :     x20 b4000078db6322d0  x21 0000000000080000  x22 0000000000000000  x23 0000000000000005
04-09 00:34:33.772  5968  5968 F DEBUG   :     x24 00000078e7d29418  x25 0000000000000006  x26 0000000000000004  x27 0000000500000000
04-09 00:34:33.772  5968  5968 F DEBUG   :     x28 00000078eae23000  x29 0000000000000000
04-09 00:34:33.772  5968  5968 F DEBUG   :     lr  00000078eaa50610  sp  00000078e7d293a0  pc  0000007a046a40e0  pst 0000000000001000
```

`cap_std` version: `1.0.12`

### PR DESCRIPTION
**Pull request by sunfishcode**
Similar to #197, do a `uname` version check before using `statx` on Android, since Android's seccomp configuration kills the process if any unrecognized system calls are used.

Fixes #311.

### CODE REVIEW

File: cap-primitives/src/rustix/linux/fs/open_impl.rs [hunk 1]
```diff
@@ -61,23 +69,6 @@ pub(crate) fn open_beneath(
...
-
-        if !CHECKED.load(Relaxed) {
-            if !openat2_supported() {
-                INVALID.store(true, Relaxed);
-                return Err(rustix::io::Errno::NOSYS.into());
-            }
-
-            CHECKED.store(true, Relaxed);
-        }
-    }
```
Comment (eddyb) [inline cap-primitives/src/rustix/linux/fs/open_impl.rs:79]: AFACIT removing this is wrong, you need to always return `NONSYS` instead.

That's because there are other callers of this function, e.g.: https://github.com/bytecodealliance/cap-std/blob/1317c28a93e8ce9d8b66d4319e705290e9a4167c/cap-primitives/src/rustix/linux/fs/stat_impl.rs#L11-L23

Comment (eddyb) [reply cap-primitives/src/rustix/linux/fs/open_impl.rs:79]:
```rust
pub(crate) fn open_beneath(
    start: &fs::File,
    path: &Path,
    options: &OpenOptions,
) -> io::Result<fs::File> {
    #[cfg(target_os = "android")]
    {
        return Err(rustix::io::Errno::NOSYS.into());
    }
```

This fix definitely works (tested on an actual Android impl that hit both `openat2` and `statx` issues before now - an Oculus Quest 2, which makes this an extremely side-tracked thing for me so I will very likely not be opening a PR myself).

Comment (sunfishcode) [reply cap-primitives/src/rustix/linux/fs/open_impl.rs:79]: Thanks for the report! Confirmed that this what's happening. I've now filed https://github.com/bytecodealliance/cap-std/pull/316 to fix this, and disable `openat2` on Android entirely with a `cfg`.
